export const stretches = [
  {
    id: 'couch-stretch',
    name: 'Couch Stretch',
    area: 'Hip Flexors',
    technique: 'Static',
    difficulty: 3,
    baseXp: 12,
    defaultHoldSeconds: 45,
    defaultReps: 2,
    side: 'bilateral',
    cues: [
      'Back knee close to the wall or bench.',
      'Squeeze the glute on the stretching side.',
      'Do not crank through sharp knee or lower-back pain.',
    ],
  },
  {
    id: 'deep-squat-pry',
    name: 'Deep Squat Pry',
    area: 'Hips',
    technique: 'Dynamic',
    difficulty: 2,
    baseXp: 10,
    defaultHoldSeconds: 60,
    defaultReps: 1,
    side: 'both',
    cues: [
      'Keep the whole foot on the floor.',
      'Use elbows to gently open the knees.',
      'Breathe slowly and keep the spine long.',
    ],
  },
  {
    id: 'hamstring-floss',
    name: 'Hamstring Floss',
    area: 'Hamstrings',
    technique: 'Dynamic',
    difficulty: 2,
    baseXp: 9,
    defaultHoldSeconds: 30,
    defaultReps: 10,
    side: 'bilateral',
    cues: [
      'Move in and out of tension.',
      'Keep the knee soft, not locked aggressively.',
      'Stop before nerve-like tingling.',
    ],
  },
  {
    id: 'pancake-good-morning',
    name: 'Pancake Good Morning',
    area: 'Adductors',
    technique: 'Loaded mobility',
    difficulty: 4,
    baseXp: 16,
    defaultHoldSeconds: 40,
    defaultReps: 8,
    side: 'both',
    cues: [
      'Sit tall before folding.',
      'Push knees upward and keep quads active.',
      'Fold from the hips, not just the spine.',
    ],
  },
  {
    id: 'front-split-lunge',
    name: 'Front Split Lunge',
    area: 'Splits',
    technique: 'Static',
    difficulty: 4,
    baseXp: 16,
    defaultHoldSeconds: 45,
    defaultReps: 2,
    side: 'bilateral',
    cues: [
      'Square the hips forward.',
      'Use blocks or hands for support.',
      'Stay at a strong stretch, not a panic stretch.',
    ],
  },
  {
    id: 'pec-doorway',
    name: 'Doorway Pec Stretch',
    area: 'Chest',
    technique: 'Static',
    difficulty: 1,
    baseXp: 7,
    defaultHoldSeconds: 45,
    defaultReps: 2,
    side: 'bilateral',
    cues: [
      'Forearm on the doorway.',
      'Turn the chest away slowly.',
      'Keep shoulder down, not shrugged.',
    ],
  },
  {
    id: 'lat-prayer',
    name: 'Lat Prayer Stretch',
    area: 'Lats',
    technique: 'Static',
    difficulty: 2,
    baseXp: 9,
    defaultHoldSeconds: 45,
    defaultReps: 2,
    side: 'both',
    cues: [
      'Hips back, arms long.',
      'Breathe into the ribs.',
      'Keep the neck relaxed.',
    ],
  },
  {
    id: 'wrist-extension-rock',
    name: 'Wrist Extension Rocks',
    area: 'Wrists',
    technique: 'Dynamic',
    difficulty: 2,
    baseXp: 9,
    defaultHoldSeconds: 30,
    defaultReps: 12,
    side: 'both',
    cues: [
      'Palms flat, fingers forward.',
      'Rock gently into range.',
      'Useful before handstands and planche work.',
    ],
  },
  {
    id: 'bridge-wall-walk',
    name: 'Wall Bridge Opener',
    area: 'Thoracic Spine',
    technique: 'Skill prep',
    difficulty: 4,
    baseXp: 16,
    defaultHoldSeconds: 30,
    defaultReps: 4,
    side: 'both',
    cues: [
      'Move slowly and keep control.',
      'Do not force the lower back.',
      'Think shoulders and upper back first.',
    ],
  },
  {
    id: 'compression-pike',
    name: 'Seated Pike Compression',
    area: 'Compression',
    technique: 'Active mobility',
    difficulty: 4,
    baseXp: 15,
    defaultHoldSeconds: 20,
    defaultReps: 8,
    side: 'both',
    cues: [
      'Hands beside knees or shins.',
      'Lift heels without leaning backward.',
      'Fight for clean reps, not ugly reps.',
    ],
  },
];
